### ISSUE TITLE
Vreshnak gets hit by choya or whatever his name is

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#14]
So in the lizard fight, Vreshnak gets hit by Dusk (I attack him) - but also Choya. In fact, Vreshnak turned red, thus hostile, which seems to have caused Choya to attack him. This is, I believe, a similar bug to the earlier bug I reported elsewhere about Lava's mod, where the White Queen talks, meanwhile her golems turn hostile and then she attacks them. I begin to believe this may be some mod causing issues; either way I believe a possible fix may be to turn all enemies hostile at the same time. This avoids or perhaps mitigates the issue of them attacking their buddies. (Though perhaps there are other possible fixes. I just noticed this for the second time, and not in prior installations, so perhaps another mod interferes here. For instance a mod that modifies the AI.)

**Comment by RamosPabloA** [comment]
This happens because of the creature's script. I think Cho is set to attack hostile creatures despite being a neutral creature. I just added a short timer so that, instead of attacking, he waits a few seconds. This should give him enough time to flee instead of staying around to hit his friend a couple of times, haha.

**Comment by RamosPabloA** [comment]
I’ve added a patch to Cho’s script to prevent this from happening. However, if there is another mod that applies changes to creature scripts, the issue may still persist. Hopefully, this patch will resolve it in the next update.
