### ISSUE TITLE
Small issue, I think, after or during chapter 6: Fall's quest in the sewers is not completed but we can still go forward

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#21]
So I tested in a recent run various other things, but also came with Fall to the cave area under the sewers, where the ice golem is, as well as that old elf. That fight is difficult, before the portal to the spider abyss area, so I skipped it and parked Fall, to finish her quest lateron.

After entering Chapter 6, and picking up Fall again, though, when I went to the sewers area, summoning the cheeky cat (which spoke after being summoned), no enemies were in that cave area. No ice golem and neither that ancient NPC sorcerer. I could access the abyss though.

This is a bit weird, as I expected that the fight should occur since I didn't yet finish it. Perhaps this is deliberate, but it is still strange because I would expect the old Sorcerer to say something still, as otherwise Fall may not know what to do. So I would recommend that the fight here is not skipped, even if Chapter 6 is reached, so that players still have to go through it as interlude towards the abyss.

**Comment by RamosPabloA** [comment]
It was intentional that way. What I’ll do is patch this issue in the next update to make the story more logical: if Fall is in the party when visiting the Underdark but her quests haven’t been completed yet, they will be closed with a dialogue where Fall states that too much time has passed and that Alendir or the circus animals are no longer a priority for her. Instead, finding her mother is what she must focus on. She will suspect that her mother is in a place similar to the Underdark based on her instincts, but she won’t know how to get there. This way, if the party visits the sewers in the Slums and finds them empty, it won’t be a logical issue since Alendir is likely dealing with Cryonax.

If Fall is NOT in the party when the Underdark is visited and she is recruited again upon returning to Athkatla, then her unfinished quests will close with a dialogue explaining that too much time has passed and her priority is now finding her mother. Again, she will suggest that her suspicions point toward a place of darkness and evil, though she isn’t sure where that might be.

The intention is for Fall’s first three quests to be completed before visiting the Underdark. Otherwise, they will be marked as incomplete in the journal.
