### ISSUE TITLE
[A tiny issue still left, I think] Fight in the troll cave

### ISSUE THREAD

**Issue by rubyFeedback** [evancauteren/bg2-autumns-twilight-mod#8]
So I just tested the fight in the troll cave and attacked the huge ettin early on.

As a result all enemies turned hostile. I believe this makes sense: they noticed
that my party does not hold back, and begins the attack, so they should strike
back too. So that bug is now gone.

However had, Dusk would normally teleport in the allies at this point in time,
before the attack actually. This does not seem to happen. It seems that when
the enemies all turn hostile, and combat begins, Dusk does not bother with
a summon.

Could perhaps an additional subroutine be added here?

In pseudocode:

    if party attacks # my party attacked them first
      enemies turn hostile # all the enemies turn hostile and begin to attack / fight back
      dusk triggers summoning allies, unless already summoned # e. g. have to
                              # check that we haven't already summoned them yet; so,
                              # only summon them once
    end

Right now it seems I have to fight all of them without teleport-allies, if I attack early. It is trivial to avoid this, e. g. wait with any attacks, so it is really a tiny issue, if at all. But perhaps the code checks can be simple: I know too little of the game logic to add such a check myself.

**Comment by RamosPabloA** [comment]
It was intentionally designed so that the combat would begin if someone attacked in advance. It was deliberate that the act of summoning didn't happen, as Dusk must use the orb, which he only uses if he speaks with Alabarza. What I could do are two things:
* Have him use the orb even if the conversation happens.
* Have him attempt to use the orb, but Dusk loses concentration due to being in the middle of combat, and the allies can't arrive (all because of a surprise attack by CHARNAME).

**Comment by RamosPabloA** [comment]
I’ve set a notice for when Good Dusk has the orb to call Falon and Trawl. If combat starts too soon, Dusk will say that the sudden fight prevented the call to his allies, and the orb will disappear without summoning them. The only way to use the orb is to have Alabarza continue the conversation with Dusk, surprising him as Dusk uses the teleportation orb.
